"""
BIST Katilim Endeksi resmi bilesenler.
Kaynak: Borsa Istanbul — bist-participation-indices-periodic-changes.pdf (XLSX)
        https://www.borsaistanbul.com/files/bist-participation-indices-periodic-changes.pdf
"""

# ------------------------------------------------------------------ #
#  BIST KATILIM 100  (XK100) — 100 hisse, resmi liste                #
# ------------------------------------------------------------------ #
KATILIM100_TICKERS = {
    "AVOD.IS":  "A.V.O.D Gida ve Tarim",
    "AFYON.IS": "Afyon Cimento",
    "AKSA.IS":  "Aksa",
    "AKSEN.IS": "Aksa Enerji",
    "ALBRK.IS": "Albaraka Turk",
    "ALCTL.IS": "Alcatel Lucent Teletas",
    "ALKA.IS":  "Alkim Kagit",
    "ALKIM.IS": "Alkim Kimya",
    "ARDYZ.IS": "ARD Bilisim Teknolojileri",
    "ASELS.IS": "Aselsan",
    "ATATP.IS": "ATP Bilgisayar",
    "BASGZ.IS": "Baskent Dogalgaz GMYO",
    "BERA.IS":  "Bera Holding",
    "BIMAS.IS": "BIM Magazalar",
    "BIOEN.IS": "Biotrend Cevre ve Enerji",
    "BOBET.IS": "Bogazici Beton Sanayi",
    "BUCIM.IS": "Bursa Cimento",
    "CANTE.IS": "Can2 Termik",
    "CLEBI.IS": "Celebi",
    "CEMAS.IS": "Cemas Dokum",
    "CEMTS.IS": "Cemtas",
    "CIMSA.IS": "Cimsa",
    "DAPGM.IS": "DAP Gayrimenkul",
    "DARDL.IS": "Dardanel",
    "DGNMO.IS": "Doganlar Mobilya",
    "ARASE.IS": "Dogu Aras Enerji",
    "DOAS.IS":  "Dogus Otomotiv",
    "EGEEN.IS": "Ege Endustri",
    "EGGUB.IS": "Ege Gubre",
    "EREGL.IS": "Eregli Demir Celik",
    "ESCOM.IS": "Escort Teknoloji",
    "TEZOL.IS": "Europap Tezol Kagit",
    "FORMT.IS": "Formet Metal ve Cam",
    "GWIND.IS": "Galata Wind Enerji",
    "GENIL.IS": "Gen Ilac",
    "GESAN.IS": "Girisim Elektrik Sanayi",
    "GOODY.IS": "Good-Year",
    "GOZDE.IS": "Gozde Girisim",
    "GUBRF.IS": "Gubre Fabrikalari",
    "HUNER.IS": "Hun Yenilenebilir Enerji",
    "ISSEN.IS": "Isbir Sentetik Dokuma",
    "ISKPL.IS": "Isik Plastik",
    "ISDMR.IS": "Iskenderun Demir Celik",
    "JANTS.IS": "Jantsa Jant Sanayi",
    "KFEIN.IS": "Kafein Yazilim",
    "KLKIM.IS": "Kalekim Kimyevi Maddeler",
    "KRDMD.IS": "Kardemir (D)",
    "KRVGD.IS": "Kervan Gida",
    "KZBGY.IS": "Kizilbuk GYO",
    "KCAER.IS": "Kocaer Celik",
    "KONTR.IS": "Kontrolmatik Teknoloji",
    "KONYA.IS": "Konya Cimento",
    "KONKA.IS": "Konya Kagit",
    "KORDS.IS": "Kordsa Teknik Tekstil",
    "KRSTL.IS": "Kristal Kola",
    "KUTPO.IS": "Kutahya Porselen",
    "MTRKS.IS": "Matriks Bilgi Dagitim",
    "MAVI.IS":  "Mavi Giyim",
    "MEDTR.IS": "Meditera Tibbi Malzeme",
    "MIATK.IS": "MIA Teknoloji",
    "MPARK.IS": "MLP Saglik",
    "MOBTL.IS": "Mobiltel Iletisim",
    "NETAS.IS": "Netas Telekom",
    "ODAS.IS":  "Odas Elektrik",
    "ORGE.IS":  "Orge Enerji Elektrik",
    "OTKAR.IS": "Otokar",
    "OYAKC.IS": "Oyak Cimento",
    "OZKGY.IS": "Ozak GMYO",
    "PSGYO.IS": "Pasifik GMYO",
    "PGSUS.IS": "Pegasus",
    "PEKGY.IS": "Peker GMYO",
    "PENGD.IS": "Penguen Gida",
    "PENTA.IS": "Penta Teknoloji",
    "POLHO.IS": "Polisan Holding",
    "QUAGR.IS": "Qua Granite",
    "RUBNS.IS": "Rubenis Tekstil",
    "SASA.IS":  "SASA Polyester",
    "SELEC.IS": "Selcuk Ecza Deposu",
    "SRVGY.IS": "Servet GMYO",
    "SNGYO.IS": "Sinpas GMYO",
    "SMRTG.IS": "Smart Gunes Enerjisi",
    "SUNTK.IS": "Sun Tekstil",
    "SUWEN.IS": "Suwen Tekstil",
    "TKNSA.IS": "Teknosa",
    "TUKAS.IS": "Tukas",
    "TMSN.IS":  "Tumosan Motor ve Traktor",
    "TUPRS.IS": "Tupras",
    "TRCAS.IS": "Turcas Petrol",
    "THYAO.IS": "Turk Hava Yollari",
    "TRILC.IS": "Turk Ilac Serum",
    "PRKAB.IS": "Turk Prysmian Kablo",
    "TTRAK.IS": "Turk Traktor",
    "USAK.IS":  "Usak Seramik",
    "VERUS.IS": "Verusa Holding",
    "VERTU.IS": "Verusaturk Girisim",
    "VESBE.IS": "Vestel Beyaz Esya",
    "YATAS.IS": "Yatas",
    "YYLGD.IS": "Yayla Gida",
    "YEOTK.IS": "Yeo Teknoloji Enerji",
    "YUNSA.IS": "Yunsa",
}

# ------------------------------------------------------------------ #
#  BIST KATILIM 50  (XK050) — 50 hisse                               #
# ------------------------------------------------------------------ #
KATILIM50_TICKERS = {
    "AKSA.IS":  "Aksa",
    "AKSEN.IS": "Aksa Enerji",
    "ALBRK.IS": "Albaraka Turk",
    "ALKIM.IS": "Alkim Kimya",
    "ARDYZ.IS": "ARD Bilisim",
    "ASELS.IS": "Aselsan",
    "BASGZ.IS": "Baskent Dogalgaz GMYO",
    "BERA.IS":  "Bera Holding",
    "BIMAS.IS": "BIM Magazalar",
    "BIOEN.IS": "Biotrend Cevre ve Enerji",
    "BUCIM.IS": "Bursa Cimento",
    "CEMAS.IS": "Cemas Dokum",
    "CEMTS.IS": "Cemtas",
    "CIMSA.IS": "Cimsa",
    "DOAS.IS":  "Dogus Otomotiv",
    "EGEEN.IS": "Ege Endustri",
    "EREGL.IS": "Eregli Demir Celik",
    "GWIND.IS": "Galata Wind Enerji",
    "GENIL.IS": "Gen Ilac",
    "GESAN.IS": "Girisim Elektrik Sanayi",
    "GOZDE.IS": "Gozde Girisim",
    "GUBRF.IS": "Gubre Fabrikalari",
    "ISDMR.IS": "Iskenderun Demir Celik",
    "JANTS.IS": "Jantsa Jant Sanayi",
    "KRDMD.IS": "Kardemir (D)",
    "KCAER.IS": "Kocaer Celik",
    "KONTR.IS": "Kontrolmatik Teknoloji",
    "KORDS.IS": "Kordsa Teknik Tekstil",
    "MAVI.IS":  "Mavi Giyim",
    "ODAS.IS":  "Odas Elektrik",
    "OTKAR.IS": "Otokar",
    "OYAKC.IS": "Oyak Cimento",
    "OZKGY.IS": "Ozak GMYO",
    "PSGYO.IS": "Pasifik GMYO",
    "PGSUS.IS": "Pegasus",
    "QUAGR.IS": "Qua Granite",
    "SASA.IS":  "SASA Polyester",
    "SELEC.IS": "Selcuk Ecza Deposu",
    "SNGYO.IS": "Sinpas GMYO",
    "SMRTG.IS": "Smart Gunes Enerjisi",
    "TKNSA.IS": "Teknosa",
    "TUKAS.IS": "Tukas",
    "TMSN.IS":  "Tumosan Motor ve Traktor",
    "TUPRS.IS": "Tupras",
    "THYAO.IS": "Turk Hava Yollari",
    "TRILC.IS": "Turk Ilac Serum",
    "PRKAB.IS": "Turk Prysmian Kablo",
    "TTRAK.IS": "Turk Traktor",
    "VESBE.IS": "Vestel Beyaz Esya",
    "YYLGD.IS": "Yayla Gida",
}

# ------------------------------------------------------------------ #
#  BIST KATILIM 30  (XK030) — 30 hisse                               #
# ------------------------------------------------------------------ #
KATILIM30_TICKERS = {
    "AKSA.IS":  "Aksa",
    "AKSEN.IS": "Aksa Enerji",
    "ALBRK.IS": "Albaraka Turk",
    "ASELS.IS": "Aselsan",
    "BASGZ.IS": "Baskent Dogalgaz GMYO",
    "BERA.IS":  "Bera Holding",
    "BIMAS.IS": "BIM Magazalar",
    "CIMSA.IS": "Cimsa",
    "DOAS.IS":  "Dogus Otomotiv",
    "EGEEN.IS": "Ege Endustri",
    "EREGL.IS": "Eregli Demir Celik",
    "GOZDE.IS": "Gozde Girisim",
    "GUBRF.IS": "Gubre Fabrikalari",
    "ISDMR.IS": "Iskenderun Demir Celik",
    "JANTS.IS": "Jantsa Jant Sanayi",
    "KRDMD.IS": "Kardemir (D)",
    "KONTR.IS": "Kontrolmatik Teknoloji",
    "KORDS.IS": "Kordsa Teknik Tekstil",
    "MAVI.IS":  "Mavi Giyim",
    "ODAS.IS":  "Odas Elektrik",
    "OTKAR.IS": "Otokar",
    "OYAKC.IS": "Oyak Cimento",
    "PGSUS.IS": "Pegasus",
    "SASA.IS":  "SASA Polyester",
    "SNGYO.IS": "Sinpas GMYO",
    "TUPRS.IS": "Tupras",
    "THYAO.IS": "Turk Hava Yollari",
    "TTRAK.IS": "Turk Traktor",
    "VESBE.IS": "Vestel Beyaz Esya",
    "YYLGD.IS": "Yayla Gida",
}

# Geri uyumluluk alias'lari
KATILIM_TICKERS = KATILIM100_TICKERS
BIST100_TICKERS = KATILIM100_TICKERS

# ------------------------------------------------------------------ #
#  CORE: Katilim 30 = en likit / en buyuk 30 hisse (hizli analiz)    #
# ------------------------------------------------------------------ #
CORE_TICKERS = list(KATILIM30_TICKERS.keys())
